Added beforeAll warmout test
tech-stack-dev/automation-playwright-ts pull request #13
Opened 2023-08-04 15:00 UTC by Valerii-Kryvokhyzha

2023-08-04 15:25 UTC, anastasiia-liashova approved these changes

2023-08-04 18:46 UTC, VitaliiDolotov requested changes

2023-08-04 18:46 UTC, VitaliiDolotov commented on automation/base/driver/BaseDriver.ts
> +    public async executeFunc(func: any, attepmts: number) {
attempts

2023-08-04 18:46 UTC, VitaliiDolotov commented on automation/base/driver/BaseDriver.ts
> +            throw new Error(message);
Better to rethrow the actual Error object rather than just the message string. It gives more information about the error.

2023-08-07 07:44 UTC, VitaliiDolotov requested changes

2023-08-07 07:44 UTC, VitaliiDolotov commented on automation/base/driver/BaseDriver.ts
> +        if (!(error === null)) {
if (error) {
        throw error;
    }

2023-08-07 10:11 UTC, VitaliiDolotov approved these changes

2023-08-07 12:01 UTC, merged